---
Name: masqueradeconfig
---
Member:
  extensions:
    - MasqueradeMemberExtension
SecurityAdmin:
  extensions:
    - MasqueradeSecurityAdminExtension
LeftAndMain:
  extra_requirements_css:
    masquerade/css/masquerade.css:
      media: screen
